baseURL: "/"
languageCode: "en-us"
title: "Corey Wooten"
theme: hugo-profile 
canonifyURLs: true
relativeURLs: true

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
  page:
    - "HTML"
    - "RSS"

enableRobotsTXT: true

services:
  googleAnalytics:
    id: G-BP0TZ210G0
  #disqus:
    #shortname: your-disqus-shortname

pagination:
  pagerSize: 3

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  main:
    - identifier: blog
      # name: Blog
      title: Blog posts
      url: /blogs
    # weight: 1
  #  - identifier: gallery
    #  name: Gallery
    #  title: Blog posts
    #  url: /gallery
    #  weight: 2
    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
  title: "Corey Wooten"
  description: Corey Wooten’s professional portfolio showcasing expertise in engineering, Web3, cybersecurity, and technical project management.  
  # staticPath: "" # The path to serve the static files from
  favicon: /images/circuit.svg 
  hostName: "https://coreywooten.com"

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: true

  # If you want to load dynamically responsive images from Cloudinary
  # This requires your images to be uploaded + hosted on Cloudinary
  # Uncomment and change YOUR_CLOUD_NAME to the Cloud Name in your Cloudinary console
  # cloudinary_cloud_name: "YOUR_CLOUD_NAME"

  # Whether to add mathjax support on all pages. Alternatively, you can opt-in per page by adding `mathjax: true` in the frontmatter.
  mathjax: true

  # Whether the fade animations on the home page will be enabled
  animate: true

  theme:
    # disableThemeToggle: true
     defaultTheme: "dark"

  font:
    fontSize: 1rem # default: 1rem
    fontWeight: 400 # default: 400
    lineHeight: 1.5 # default: 1.5
    textAlign: left # default: left

  # color preference
  # When using hex codes for colors, quotations must be used along with the # sign
  # color:
  #   textColor: "#343a40"
  #   secondaryTextColor: "#6c757d"
  #   textLinkColor: "#007bff"
  #   backgroundColor: "#eaedf0"
  #   secondaryBackgroundColor: "#64ffda1a"
  #   primaryColor: "#007bff"
  #   secondaryColor: "#f8f9fa"

  #   darkmode:
  #     textColor: "#e4e6eb"
  #     secondaryTextColor: "#b0b3b8"
  #     textLinkColor: "#ffffff"
  #     backgroundColor: "#18191a"
  #     secondaryBackgroundColor: "#212529"
  #     primaryColor: "#ffffff"
  #     secondaryColor: "#212529"

  # If you want to customize the menu, you can change it here
  navbar:
    align: ms-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    # brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
    # showBrandLogo: false # Show brand logo in nav bar | default is true
    brandName: "Corey Wooten" # Brand name for the brand | default is the title variable
    disableSearch: true
    # searchPlaceholder: "Search"
    stickyNavBar:
      enable : true
      showOnScrollUp : true
    enableSeparator: false
    menus:
      disableAbout: false
      disableExperience: false
      disableEducation: false
      disableProjects: false
      disableAchievements: false
      disableContact: false

  # Hero
  hero:
    enable: true
    intro: "Hello,"
    title: "I'm Corey."
    subtitle: "Strategic. Technical. Forward-thinking. ⚡️"
    content: "Tech-savvy builder and strategist blending engineering with creative problem-solving. I turn complex challenges into clean, scalable systems; always with an eye toward what’s next. Proven success launching scalable systems, optimizing operations, and leading global initiatives that bridge innovation with real-world impact."
    image: /images/corey-7sd.png
    bottomImage:
      enable: true
    # roundImage: true # Make hero image circular | default false
    button:
      enable: false
      name: "Resume"
      url: "#"
      download: false
      newPage: false
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/corey-wooten
        - icon: fab fa-linkedin
          url: https://linkedin.com/in/coreywooten


  # About
  about:
    enable: true
    title: "💡 About Me"
    image: "/images/me-2.png"
    content: |-
      I’m a curious, solutions-first kind of person with a background in engineering, Web3, and digital systems. I’ve worked across startups and global teams, launching platforms, refining ops, and translating technical goals into real-world results. 
      
      I enjoy building things that actually work and making the process smoother for everyone involved. Whether it’s designing solutions, leading projects, or breaking down complex ideas, I bring both strategy and execution to the table. 
      
      I hold a Bachelor's degree in Computer Systems Technology and an MBA conecentrated in Cybersecurity. Further, I’m focused on leading innovative, future-ready teams. If it involves innovation, collaboration, and strategic thinking, I’m all in.

    skills:
      enable: true
      title: "Here are a few technologies I've worked with:"
      items:
        - "Atlassian (Confluence, Jira, Trello)"
        - "AWS & Azure"
        - "Blockchain (RPC, APIs)"
        - "Git & Github"
        - "Grafana & Splunk"
        - "HTML/CSS"
        - "SQL"
        - "Tableau"

  # Experience
  experience:
    enable: true
    title: "📌 Experience"
    items:
      - job: "Certified Personal Trainer and Nutrition Coach"
        company: "ClubFitness"
        companyUrl: "https://clubfitnessgso.com"
        date: "Jul 2024 - Present"
        featuredLink:
          enable: false
          name: "View the project"
          url: "https://example.com"
        content: |-
          - Managed a portfolio of 20+ clients with Trainerize, applying cloud-based program design, real-time performance tracking, and asynchronous communication channels to personalize fitness plans and monitor progress data.
          - Scaled client acquisition to 50+ within six (6) months through targeted outreach, data-driven programming, and personalized onboarding workflows that prioritized long-term adherence and measurable outcomes.
          - Developed adaptive fitness solutions for clients aged 16-84, integrating biometric feedback and mobility assessments; notably improved an elderly client's mobility to eliminate reliance on assisted walking devices.

      - job: "Professional Development and Career Transition"
        company: "Career Break"
        companyUrl: null
        date: "Oct 2023 - Jul 2024"
        featuredLink:
          enable: false
          name: "View the project"
          url: "https://example.com"
        content: |-
          - Completed an MBA concentrated in Cybersecurity while earning certifications in Personal Training, Nutrition Coaching, and CPR/First Aid, blending leadership, wellness, and technical growth.
          - Led freelance web design projects that strengthened creative problem-solving, client communication, and technical execution. 
          - Reinvested in long-term career goals by exploring roles across tech, engineering, and themed entertainment, enhancing adaptability and strategic thinking.

      - job: "Evolving Roles"
        company: "Ankr"
        companyUrl: "https://ankr.com"
        date: "Dec 2021 - Oct 2023"
        featuredLink:
          enable: false
          name: "View Deliverable"
          url: "http://status.ankr.com"
        content: |-
          
            ###### Lead Product Success Engineer (Jul 2022 - Oct 2023)
            - Developed and launched a real-time Grafana dashboard to monitor 40+ blockchain RPC networks, boosting infrastructure reliability and visibility. 
            - Drove a 95%+ customer satisfaction rate by optimizing technical documentation and support systems, enabling efficient resolution of complex issues. 
            - Acted as a strategic liaison between Sales, Product, and DevOps, guiding the development of Web3 solutions for 10+ emerging blockchain companies.
          
            ###### Technical Program Manager (Dec 2021 - Jul 2022)
            - Streamlined the documentation pipeline by integrating GitHub Pull Request workflows with Visual Studio Code, cutting review and deployment time by 35%. 
            - Increased user engagement by 20% through strategic content enhancements and technical education initiatives. 
            - Produced a series of educational Web3 videos to drive awareness around digital wallets, decentralized gaming, and emerging blockchain technologies.

      - job: "Evolving Roles"
        company: "GPX Intelligence"
        companyUrl: "https://gpx.co"
        date: "Feb 2020 - Nov 2021"
        featuredLink:
          enable: false
          name: "View the project"
          url: "https://example.com"
        content: |-
        
            ###### Records Manager (Feb 2021 - Nov 2021)
            - Built and implemented the company's first integrated legal inquiry database, reducing claim response times by roughly 36 hours. 
            - Handled ethical data collection and reporting for multiple claims each week for law enforcement, attornies, and government agencies.
         
            ###### RMA Coordinator (May 2020 - Feb 2021)
            - Managed and processed 25+ daily returns in WooCommerce, issuing refunds, refurbishing, and restocking devices to maintain quality control. 
            - Developed a standardized RMA process using automations and platform integrations, curring return handling time by over 10 hours.  

            ###### IoT Customer Success and Product Specialist (Feb 2020 - Nov 2021)
            - Diagnosed and resolved technical issues for 50+ GPS-enabled devices daily using IoT platforms (Hologram, Twilio, AT&T, Verizon). 
            - Crafted 100+ Zendesk macros with Liquid Markup, reducing support response times by six (6) hours wihtin one (1) month. 
          
      - job: "Founder and CEO"
        company: "Mind Body Muscle"
        companyUrl: "https://corey-wooten.wixsite.com/website"
        date: "Feb 2017 - Mar 2020"
        info:
          enable: false
        featuredLink:
          enable: false
          url: "https://example.com"
        content: |
          - Founded a direct-to-consumer fitness brand and launched two physical products via Shopify and Amazon FBA, scaling to $15.5K in quarterly sales and increasing revenue by 35% over two (2) quarters.
          - Engineered SEO-optimized marketing funnels and analytics-backed campaigns, increasing site traffic by 40% and improving conversion rates through targeted keyword strategies and customer behavior tracking.
          - Orchestrated end-to-end global supply chain operations, coordinating with international vendors to import 1,000+ units per batch while ensuring compliance with customs and logistics regulations.

  # Education
  education:
    enable: true
    title: "📚 Education"
    index: false
    items:
      - title: "Master of Business Administration (MBA)"
        school:
          name: "University of North Carolina at Wilmington"
          url: "https://uncw.edu"
        date: " "
        GPA: "3.83 out of 4.00"
        content: |-
            *Cybersecurity Concentration*
            
            **Acquired Skills**
            
            ###### Strategic and Analytical
              - Business intelligence and data interpretation
              - Predictive modeling and Statistical Analysis (JMP Pro, Excel) 
              - Financial Modeling and valuation techniques (Excel) 
              - Strategic planning and performance measurement 
              - Legal and regulatory risk assessment 
            
            ###### Cybersecurity and Technical
              - Threat detection, logging, and monitoring (Microsoft Sentinel, Splunk) 
              - Network traffic analysis (TShark, Wireshark) 
              - Cybersecurity strategy development and governance 
              - Risk management and incident response frameworks 
              - Data privacy and compliance 
           
            ###### Data and Information Management
              - Relational database design and querying (Microsoft Access) 
              - Data visualization and storytelling (Canva, Excel, PowerPoint)
              - Workflow documentation and process automation 
              - Cloud-based collaboration and file management (OneDrive, Teams) 

            ###### Cross-Functional Business Tools
              - CRM insights and customer segmentation 
              - Go-to-market planning and marketing analytics
              - Supply chain optics and operational decision-making 
              - Public speaking and executive-level presentations (PowerPoint, YouTube)
           
      - title: "Bachelor of Science (BS) in Computer Systems Technology"
        school:
          name: "North Carolina A&T State University"
          url: "https://ncat.edu"
        date: " "
        GPA: "3.75 out of 4.00"
        content: |-
          **Activities and Accomplishments**
            - Magna Cum Laude Honors
            - NCAT Electronics Club 
            - UNCF HBCU Innovation Summit 
            - CIEE: Business and Culture Shanghai (Study Abroad)

        featuredLink:
          enable: false
          name: "My academic record"
          url: "https://example.com"

  # Achievements
  achievements:
    enable: true
    title: "🏆 Achievements"
    items:
      - title: AWS Cloud for Technical Professionals
        content: Trailhead by Salesforce
        url: https://salesforce.com/trailblazer/coreywooten
        image: /images/achievement.jpg
      - title: Facebook Hackathon Winner
        content: Developed a product using Artificial Intelligence.
        image: /images/achievement.jpg
      - title: Hugo Profile
        content: Developed a theme and getting 1K+ downloads per month.
        url: "https://github.com/gurusabarish/hugo-profile"
        image: /images/achievement.jpg
      - title: Microsoft Imagine Runner
        content: We are developed a product which can help others.
      - title: Google Summer of Code
        content: Contributed to a open source project.
        url: https://example.com

  # projects
  projects:
    enable: true
    title: "🛠️ Projects"
    items:
      - title: Portfolio Revamp (2025)
        content: Rebuilt my professional portfolio from scratch using VS Code, GitHub, and Vercel; migrating from Wix to a custom Hugo static site.
        image: /images/blogs/portfolio.png
        featured:
          name: View Details
          link: /blogs/portfolio-revamp
        badges:
          - "Hugo"
          - "VS Code"
          - "GitHub" 
          - "Vercel" 
          - "CI/CD"
        links:
          - icon: fab fa-github
            url: https://www.github.com/corey-wooten/portfolio

      - title: Image Converter
        content: A web app to convert image to pdf, png to jpg, png to jpg and png to webp without database using django.
        image: /images/projects/converter.jpg
        featured:
          name: Demo
          link: https://django-converter.herokuapp.com
        badges:
          - "Django"
          - "Bootstrap"
        links:
          - icon: fab fa-github
            url: https://github.com/gurusabarish/converter

      - title: Hugo Profile V2
        content: A clean and simple Hugo template for personal portfolio and blog.
        image: /images/projects/profile2.jpg
        featured:
          name: Demo V2
          link: https://hugo-profile-2.netlify.app
        badges:
          - "Hugo"
          - "Bootstrap"
          - "Javascript"
        links:
          - icon: fab fa-github
            url: https://github.com/gurusabarish/HugoProfileV2

  #Contact
  contact:
    enable: true
    title: "📥 Let's Connect"
    content: Click the button below to send me an email and I'll get back to you as soon as possible.
    btnName: Get in Touch
    btnLink: mailto:corey@coreywooten.com
    # formspree:
    #   enable: true # `contact.email` value will be ignored
    #   formId: abcdefgh # Take it from your form's endpoint, like 'https://formspree.io/f/abcdefgh'
    #   emailCaption: "Enter your email address"
    #   messageCaption: "Enter your message here"
    #   messageRows: 5

  footer:
    recentPosts:
      path: "blogs"
      count: 3
      title: Recent Posts
      enable: true
      disableFeaturedImage: true
    socialNetworks: 
      github: "https://github.com/corey-wooten"
      linkedin: "https://linkedin.com/in/coreywooten"
      

  # List pages like blogs and posts
  listPages:
    disableFeaturedImage: false

  # Single pages like blog and post
  singlePages:
    socialShare: true
    readTime:
      enable: true
      content: "min read"
    scrollprogress:
      enable: true
    tags:
      openInNewTab: true

  # For translations
  terms:
    read: "Read"
    toc: "Table Of Contents"
    copyright: "All rights reserved"
    pageNotFound: "Page not found"
    emailText: "Check out this site"

  datesFormat:
    article: "Jan 2, 2006"
    articleList: "Jan 2, 2006"
    articleRecent: "Jan 2, 2006"

  #customScripts: -| # You can add custom scripts which will be added before </body> tag
  #  <script type="text/javascript"><!-- any script here --></script>
