[build]
  publish = "public"
  command = "hugo --gc --minify --buildFuture --themesDir themes/" 

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[context.production.environment]
  HUGO_VERSION = "0.145.0"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[context.split1]
  command = "hugo --gc --minify --enableGitInfo --themesDir themes/"

[context.split1.environment]
  HUGO_VERSION = "0.145.0"
  HUGO_ENV = "production"

[context.deploy-preview]
  command = "hugo --gc --minify --buildFuture --themesDir themes/ -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.145.0"

[context.branch-deploy]
  command = "hugo --gc --minify --themesDir themes/ -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
  HUGO_VERSION = "0.145.0"

[context.next.environment]
  HUGO_ENABLEGITINFO = "true"